#!/usr/bin/env python3
"""Generates the blue noise threshold tile used by the "blue noise" dithering mode
(port/boards/playdate/bluenoise.h), with Ulichney's void-and-cluster method on a torus.

    scripts/gen-bluenoise.py > port/boards/playdate/bluenoise.h

The tile is N x N (a power of two, N >= 8 so a row is a whole number of LCD bytes). Every
pixel gets a distinct rank 0..N*N-1 such that, for any threshold, the pixels below it are
spread as evenly as possible. The ranks are then mapped to thresholds 0..254, so the
display's `luminance > threshold` test gives all black for 0 and all white for 255, with
white pixels in proportion to the luminance in between.
"""
import math
import random
import sys

N = 32
SIGMA = 1.5
RADIUS = 6  # the kernel reaches 4 sigma
SEED = 20261003


def main():
    random.seed(SEED)
    n2 = N * N
    kernel = [(dx, dy, math.exp(-(dx * dx + dy * dy) / (2 * SIGMA * SIGMA)))
              for dy in range(-RADIUS, RADIUS + 1) for dx in range(-RADIUS, RADIUS + 1)]

    def splat(energy, i, sign):
        x, y = i % N, i // N
        for dx, dy, w in kernel:
            energy[((y + dy) % N) * N + (x + dx) % N] += sign * w

    def energy_of(pattern, value):
        e = [0.0] * n2
        for i in range(n2):
            if pattern[i] == value:
                splat(e, i, 1)
        return e

    def tightest(energy, pattern, value):  # the pixel of `value` with the most energy around it
        return max((i for i in range(n2) if pattern[i] == value), key=lambda i: energy[i])

    def largest_void(energy, pattern, value):  # the pixel of `value` with the least
        return min((i for i in range(n2) if pattern[i] == value), key=lambda i: energy[i])

    # initial pattern: ~10% ones, relaxed until the tightest cluster is also the largest void
    bp = [0] * n2
    for i in random.sample(range(n2), n2 // 10):
        bp[i] = 1
    e = energy_of(bp, 1)
    while True:
        c = tightest(e, bp, 1)
        bp[c] = 0
        splat(e, c, -1)
        v = largest_void(e, bp, 0)
        bp[v] = 1
        splat(e, v, 1)
        if v == c:
            break
    ones = sum(bp)

    rank = [0] * n2
    # phase 1: remove ones from the tightest clusters, ranks ones-1 .. 0
    p = bp[:]
    e = energy_of(p, 1)
    for r in range(ones - 1, -1, -1):
        c = tightest(e, p, 1)
        p[c] = 0
        splat(e, c, -1)
        rank[c] = r
    # phase 2: add ones into the largest voids, ranks ones .. n2/2 - 1
    p = bp[:]
    e = energy_of(p, 1)
    for r in range(ones, n2 // 2):
        v = largest_void(e, p, 0)
        p[v] = 1
        splat(e, v, 1)
        rank[v] = r
    # phase 3: the rest, by the tightest clusters of zeros
    e = energy_of(p, 0)
    for r in range(n2 // 2, n2):
        c = tightest(e, p, 0)
        p[c] = 1
        splat(e, c, -1)
        rank[c] = r

    assert sorted(rank) == list(range(n2))
    thr = [r * 255 // n2 for r in rank]

    out = sys.stdout
    out.write("/* Generated by scripts/gen-bluenoise.py (void-and-cluster, %dx%d, sigma %.1f, seed %d): do not edit. */\n"
              % (N, N, SIGMA, SEED))
    out.write("#define BLUENOISE_SIZE %d\n\n" % N)
    out.write("static const uint8_t bluenoise[BLUENOISE_SIZE * BLUENOISE_SIZE] = {\n")
    for y in range(N):
        out.write("\t" + ",".join("%d" % t for t in thr[y * N:(y + 1) * N]) + ",\n")
    out.write("};\n")


if __name__ == "__main__":
    main()
